#!/bin/bash

if [ $# -gt 0 ]; then
    USER=$1
    echo $USER
else
    echo "Please Enter the valid parameters "
fi

#ADDING_USER

#!/bin/bash

if [ $# -gt 0 ]; then
  for USER in $@;    do
     echo $USER 

#alphabet_order_Setup

      if [[ $USER =~ ^[a-zA-Z]+$ ]]
      then
        EXISTING_USER=$(cat /etc/passwd | grep -i -w $USER | cut -d ":" -f1)
        if [ "${USER}" ] = ["${EXISTING_USER}"]
        then
           echo "the $USER you entered is already present in the machine, please enter the another name"
        else
             echo "lets create a new $USER"
             sudo useradd -m $USER --shell /bin/bash

#first_fixing_special character
#second pipe is to take one special character
#third pipe is for shuffle to avoid repeat characters
#fourth pipe is for taking head value

             SPEC=$(echo '!@#$%*&' | fold -w1 | shuf | head -1)
             PASSWORD= " Indianarmy@${RANDOM}${SPEC}"
             echo "$USER:$PASSWORD" | sudo chpasswd
             echo "the temprory password the $USER is ${PASSWORD}"
             passwd -e $USER
       fi
    else 
        echo "The user must contain Alphabets"
    fi
  done

else
    echo "Please Enter the valid parameters "
fi
